### This is a demo on Jupyter Notebooks and the numpy module in Python
We'll add all examples in code cells and run iteratively.

In [3]:
# This is our code cell. It's the first one in this notebook so we'll do some setup here.
# p. 229
import sys
import numpy as np
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [20, 30, 40]]
a = np.array(data)  # create array from nested sequences
print(a, '\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [20 30 40]] 



In [4]:
print("a.ndim (# dimensions):", a.ndim)  # get number of dimensions
print("a.shape (lengths of axes/dimensions):", a.shape)  # get shape
print("a.size (number of elements in array):", a.size)
print("a.itemsize (size of one item):", a.itemsize)
print("a.nbytes (number of bytes used):", a.nbytes)
print("sys.getsizeof(data):", sys.getsizeof(data))
print()

a.ndim (# dimensions): 2
a.shape (lengths of axes/dimensions): (4, 3)
a.size (number of elements in array): 12
a.itemsize (size of one item): 4
a.nbytes (number of bytes used): 48
sys.getsizeof(data): 88



In [7]:
a_zeros = np.zeros((3, 5), dtype=np.uint32)  # create array of specified shape and datatype, initialized to zeroes
print(a_zeros)
print()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]



In [8]:
a_ones = np.ones((2, 3, 4, 5))  # create array of specified shape, initialized to ones
print(a_ones)
print()

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]



### np.empty
NumPy's empty() function creates an array without initializing its values to any specific value. This means the array will contain whatever random values were present in the allocated memory.

In [14]:
# with uninitialized values
a_empty = np.empty((3, 8))  # create uninitialized array of specified shape
print(a_empty)
print(a.dtype)  # defaults to float64

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.01101285e-307
  1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306]
 [1.37962320e-306 1.29060871e-306 2.22518251e-306 1.33511969e-306
  1.78022342e-306 1.05700345e-307 3.11525958e-307 1.69118108e-306]
 [8.06632139e-308 1.20160711e-306 1.69119330e-306 8.90100844e-307
  1.69121367e-306 2.13620807e-306 1.69120552e-306 6.23058028e-307]]
int32


In [15]:
nan_array = np.full((5, 10), np.NaN)  # create array of NaN values
print(nan_array)

[[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
