In [2]:
# p. 272 numpy save text and load text
import numpy as np

sample_data = np.loadtxt(   # Load data from space-delimited file
    "./files/columns_of_numbers.txt",
    skiprows=1,
    dtype=float
)

print(sample_data)

[[63. 51. 59. 61. 50.  4.]
 [40. 66.  9. 64. 63. 17.]
 [18. 23.  2. 61.  1.  9.]
 ...
 [26. 20. 54. 46. 38. 23.]
 [ 9.  5. 59. 23.  2. 26.]
 [46. 34. 25.  8. 39. 34.]]


In [3]:
#modify the sample data
sample_data  /= 10  # Modify sample data
print(sample_data)

[[6.3 5.1 5.9 6.1 5.  0.4]
 [4.  6.6 0.9 6.4 6.3 1.7]
 [1.8 2.3 0.2 6.1 0.1 0.9]
 ...
 [2.6 2.  5.4 4.6 3.8 2.3]
 [0.9 0.5 5.9 2.3 0.2 2.6]
 [4.6 3.4 2.5 0.8 3.9 3.4]]


#### Write data to text file as floats, rounded to two decimal places, using commas as delimiter

In [4]:
float_file_name = './files/save_data_float.txt'

np.savetxt(float_file_name, sample_data, delimiter=",", fmt="%5.2f")  

### int version
Write data to text file as ints, using commas as delimiter

In [5]:
int_file_name = './files/save_data_int.txt'

np.savetxt(int_file_name, sample_data, delimiter=",", fmt="%d")

Read data back into ndarray

In [6]:
data = np.loadtxt(float_file_name, delimiter=",")  
print(data)

[[6.3 5.1 5.9 6.1 5.  0.4]
 [4.  6.6 0.9 6.4 6.3 1.7]
 [1.8 2.3 0.2 6.1 0.1 0.9]
 ...
 [2.6 2.  5.4 4.6 3.8 2.3]
 [0.9 0.5 5.9 2.3 0.2 2.6]
 [4.6 3.4 2.5 0.8 3.9 3.4]]
